# Generated by Django 5.2.8 on 2026-01-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petalcart', '0005_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('flower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petalcart.flower')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petalcart.flowershop')),
            ],
        ),
    ]
