# Generated by Django 5.2.8 on 2026-01-19 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petalcart', '0005_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
