# Generated by Django 5.2.8 on 2026-01-21 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petalcart', '0005_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='petalcart.cart'),
        ),
    ]
