# Generated by Django 5.2.8 on 2026-02-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petalcart', '0006_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
