# Generated by Django 5.2.8 on 2026-01-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petalcart', '0006_remove_cart_id_remove_order_id_cart_cart_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
